
 #
 #   ██████╗ ██╗   ██╗██████╗     ██████╗ ███████╗██╗   ██╗██╗███████╗███████╗
 #  ██╔═══██╗██║   ██║██╔══██╗    ██╔══██╗██╔════╝██║   ██║██║██╔════╝██╔════╝
 #  ██║   ██║██║   ██║██████╔╝    ██████╔╝█████╗  ██║   ██║██║███████╗█████╗
 #  ██║▄▄ ██║██║   ██║██╔══██╗    ██╔══██╗██╔══╝  ╚██╗ ██╔╝██║╚════██║██╔══╝
 #  ╚██████╔╝╚██████╔╝██║  ██║    ██║  ██║███████╗ ╚████╔╝ ██║███████║███████╗
 #   ╚══▀▀═╝  ╚═════╝ ╚═╝  ╚═╝    ╚═╝  ╚═╝╚══════╝  ╚═══╝  ╚═╝╚══════╝╚══════╝
 #
 #  by qbit
 #

# Локация, куда будет телепортировать игрока на проверке
# Формат: world;x;y;z;yaw;pitch
spawn-location: "spawn;0.5;90;0.5;180;0"

revise-time: 180
extra-time: 120 # доп время

revise-messages:
  delay: 10
  discord:
    - ""
    # сообщения при проверке через discord — заполни сам
    - ""
  anydesk:
    - ""
    # сообщения при проверке через anydesk — заполни сам
    - ""

title: ";&"
bossbar:
  text: "&7Осталось: &f{timer}"
  rt-text: "&7Таймер отключён"
  color: RED
  style: SOLID

list:
  empty: "Нет активных проверок."
  header: "Активные проверки:"
  line: "{i}. {admin} -> {player} ({time}) ({type})"

# События при ливе с проверки
player-leave:
  disconnect: true
  kick: true
  log: "Игрок {player} вышел с проверки у {admin}"
  command: ""
  broadcast:
    ban:
      - ""
    rt:
      - ""

# События при истечении времени
time-leave:
  log: "У {player} закончилось время на проверке"
  command: ""

# Отмена ивентов
#   true - отменить
#   false - не отменять
event-cancel:
  move: true
  item-drop: true
  item-consume: true
  inventory-click: true
  chat:
    cancel: true
    send-to-contact: true # перенаправлять ли сообщение в чат в /contact <msg>
  teleport: true
  command:
    cancel: true
    msg: ""
    whitelist:
      - contact



contact-format:
  from-admin: "&7[Контакт] &f{message} &7(Админ)"
  from-player: "&7[Контакт] &f{message} &7({player})"